package com.aivox.base.common;

import androidx.core.view.InputDeviceCompat;
import com.aivox.besota.bessdk.BesSdkConstants;
import com.aivox.besota.bessdk.service.BesOTAConstants;
import org.videolan.libvlc.MediaDiscoverer;
import org.videolan.libvlc.MediaPlayer;
import org.videolan.libvlc.RendererDiscoverer;
import org.videolan.libvlc.interfaces.IMediaList;

/* JADX INFO: loaded from: classes.dex */
public enum GlassesCmd {
    GET_DEVICE_INFO(1),
    GET_PRODUCT_MODEL(2),
    GET_VERSION(3),
    GET_HARDWARE_INFO(4),
    GET_SUPPORTED_FEATURES(5),
    GET_DEVICE_NAME(6),
    HEART_BEAT(7),
    GET_BATTERY(257),
    REPORT_BATTERY(MediaPlayer.Event.Opening),
    GET_NOISE_CONTROL_STATUS(InputDeviceCompat.SOURCE_DPAD),
    SWITCH_NOISE_CONTROL(IMediaList.Event.ItemDeleted),
    REPORT_NOISE_STATUS(515),
    GET_WEARING_STATUS(BesSdkConstants.BES_TOTA_CONFIRM),
    SET_WEARING_DETECTION(BesSdkConstants.BES_TOTA_SUCCESS),
    GET_GAME_MODE(1025),
    SET_GAME_MODE(1026),
    REPORT_GAME_MODE(1027),
    GET_EQ(MediaDiscoverer.Event.Ended),
    SET_EQ(RendererDiscoverer.Event.ItemAdded),
    GET_BUTTON_CONFIG(1537),
    SET_BUTTON_FUNCTION(1538),
    FIND_DEVICE(1793),
    REPORT_FIND_STATUS(1794),
    APP_AI_MODE(2049),
    DEVICE_AI_MODE(2050),
    AI_MODE_EVENT(2051),
    AI_MODE_VOICE_START(2052),
    AI_MODE_VOICE_EVENT_TRIGGER(2053),
    AI_MODE_VOICE_PROMPT(2054),
    SET_WIFI_SSID(BesOTAConstants.OTA_CMD_GET_PROTOCOL_VERSION),
    SET_WIFI_PASSWORD(BesOTAConstants.OTA_CMD_SET_OAT_USER_OK),
    SET_TIME(BesOTAConstants.OTA_CMD_GET_HW_INFO),
    REPORT_WIFI_STATUS(BesOTAConstants.OTA_CMD_SET_UPGRADE_TYPE_NORMAL),
    FILE_COUNT_UPDATE(BesOTAConstants.OTA_CMD_SET_UPGRADE_TYPE_FAST),
    IMAGE_CAPTURE_START(BesOTAConstants.OTA_CMD_ROLESWITCH_GET_RANDOMID),
    IMAGE_CAPTURE_FINISH(BesOTAConstants.OTA_CMD_SELECT_SIDE_OK),
    VIDEO_API(BesOTAConstants.OTA_CMD_BREAKPOINT_CHECK_80),
    DISK_CAPACITY(BesOTAConstants.OTA_CMD_BREAKPOINT_CHECK_80_NO_CHANGE),
    VIDEO_PREVIEW_CONTROL(2314),
    WIFI_AP_CONTROL(2315),
    REPORT_AP_SSID(2316),
    REPORT_AP_PASSWORD(2317),
    REPORT_WIFI_API(2318),
    SET_BINDING_CODE(2319),
    GET_BINDING_CODE(BesOTAConstants.OTA_CMD_BREAKPOINT_CHECK),
    CLEAR_NOT_UPLOAD_FILE(BesOTAConstants.OTA_CMD_SEND_CONFIGURE_OK),
    CLEAR_RESULT_UPLOAD(BesOTAConstants.OTA_CMD_SEND_VERIFY_BTN_OK),
    WIFI_RUNNING_STATUS_REPORT(BesOTAConstants.OTA_CMD_DISCONNECT),
    SET_ANTI_SHAKE(BesOTAConstants.OTA_CMD_SEND_OTA_DATA),
    GET_ANTI_SHAKE(BesOTAConstants.OTA_CMD_CRC_CHECK_PACKAGE),
    GET_FILE_COUNT(BesOTAConstants.OTA_CMD_CRC_CHECK_PACKAGE_OK),
    REPORT_AP_MAC_ADDRESS(BesOTAConstants.OTA_CMD_WHOLE_CRC_CHECK),
    GET_CALL_STATUS(2561),
    BLE_AUDIO_CONTROL(2562),
    BLE_AUDIO_DATA(2563),
    GET_OTA_INFO(2817),
    REPORT_HARDWARE_VERSION(2818),
    START_OTA(2819),
    COMPLETE_OTA(2820),
    START_GET_FILE(3073),
    FILE_DATA_UPLOAD(3074),
    FILE_UPLOAD_END(3075),
    RETRIEVE_FILE_DATA(3076),
    SET_DEVICE_CONTROL(3329),
    LOCAL_VIDEO_RECORD_STATUS_REPORT(3330),
    GET_FILE_LIST_AND_DISK_INFO(3585),
    DELETE_FILE(3586),
    DELETE_ALL_FILE(3587),
    LOCAL_RECORD_CONTROL(3588),
    LOCAL_AUDIO_RECORD_STATUS_REPORT(3589),
    LOCAL_RECORD_PROMPT_SET(3590),
    GET_LOCAL_RECORD_PROMPT_STATUS(3591),
    LOCAL_RECORD_FILE_COUNT_REPORT(3592),
    GET_WAKE_UP_FUNCTION_LIST(3841),
    GET_WAKE_UP_SETTING(3842),
    SET_WAKE_UP_SETTING(3843);

    private final int cmd;

    GlassesCmd(int i) {
        this.cmd = i;
    }

    public int getCmd() {
        return this.cmd;
    }
}
